// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCCyDWjee9k0IpfGZp7LwhVr0BhWmQM60',
    appId: '1:806667950412:web:c4404bbccbed369cae97e9',
    messagingSenderId: '806667950412',
    projectId: 'takenotes-flutter-project',
    authDomain: 'takenotes-flutter-project.firebaseapp.com',
    storageBucket: 'takenotes-flutter-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIstsjKlzlNyLM-q2UW_--8QvLUmjFw8s',
    appId: '1:806667950412:android:469303693dcedca1ae97e9',
    messagingSenderId: '806667950412',
    projectId: 'takenotes-flutter-project',
    storageBucket: 'takenotes-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUcBX6YTun9qGP06Bpn9LpklmOkQdTayg',
    appId: '1:806667950412:ios:abd6346c270449deae97e9',
    messagingSenderId: '806667950412',
    projectId: 'takenotes-flutter-project',
    storageBucket: 'takenotes-flutter-project.appspot.com',
    iosClientId: '806667950412-7i8ub0ljqi6q67akb8h73l1ij53q2fcs.apps.googleusercontent.com',
    iosBundleId: 'com.atencia.takenote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUcBX6YTun9qGP06Bpn9LpklmOkQdTayg',
    appId: '1:806667950412:ios:abd6346c270449deae97e9',
    messagingSenderId: '806667950412',
    projectId: 'takenotes-flutter-project',
    storageBucket: 'takenotes-flutter-project.appspot.com',
    iosClientId: '806667950412-7i8ub0ljqi6q67akb8h73l1ij53q2fcs.apps.googleusercontent.com',
    iosBundleId: 'com.atencia.takenote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCCyDWjee9k0IpfGZp7LwhVr0BhWmQM60',
    appId: '1:806667950412:web:0abd3760c3bdb195ae97e9',
    messagingSenderId: '806667950412',
    projectId: 'takenotes-flutter-project',
    authDomain: 'takenotes-flutter-project.firebaseapp.com',
    storageBucket: 'takenotes-flutter-project.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDCCyDWjee9k0IpfGZp7LwhVr0BhWmQM60',
    appId: '1:806667950412:web:8a84f9025ae79dd1ae97e9',
    messagingSenderId: '806667950412',
    projectId: 'takenotes-flutter-project',
    authDomain: 'takenotes-flutter-project.firebaseapp.com',
    storageBucket: 'takenotes-flutter-project.appspot.com',
  );
}
